//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RafUrun
    {
        public int RafUrunID { get; set; }
        public Nullable<int> RafID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Raf Raf { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
